[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "dbcf84c08df6cc003a11350fe0f90fd1755e2b71"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "581ef032828ea65effc19e1ad92a48321ea55714e929c8c7811f2f7f807ed32a"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.aarch64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "376357632d64b5471f06eef12c728bfcef85590c"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "ead1aeba507973572b7e7a64ce132cdec6f091833137cf624a4ed0e18d5b0dac"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.aarch64-linux-musl.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "714df3cd0b2d827ff8ff00c0b8d801aa9175f64b"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "7951a589812629d98bb861491ffeb2adcea1c82b14f51671faba9b9257c8eefc"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.x86_64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "i686"
git-tree-sha1 = "9fbb3f93dc5b0bfebb0ef233badaf3fee310a683"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "7639e7dad7a6138d8e074cded5354d087825be6351173b8590b13a5991aa44a2"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.i686-linux-gnu.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "45248f25cfab7c21ee8713d3b8d8ea9b0160c008"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "7bad57cc41fac8de3b80879aecc7d02564154c984aaefcd48a8963e8fbc1610a"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.x86_64-linux-musl.tar.gz"
[[Libuuid]]
arch = "powerpc64le"
git-tree-sha1 = "840f93e297a363adacea2eb103560bfae12c9607"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "41b9fce387a1333dc871cc53dc482ceea7982728e5e28b54d4b8e8df2584ba3d"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.powerpc64le-linux-gnu.tar.gz"
[[Libuuid]]
arch = "i686"
git-tree-sha1 = "7a6f8c952e84450fa37e241c7e724c788e2305ec"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "ac72f81bc0a746972255da7dd601b906037514f789e0646c1971efd794aa8d94"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.i686-linux-musl.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "210b2fb7c45a978ee95dea7db6ea88aedc6e56d1"
os = "freebsd"

    [[Libuuid.download]]
    sha256 = "1e93209a96bd52d371a964310cb4f04ec6b9308e5f3dd9fc617a32a7f94da2c4"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libuuid]]
arch = "armv7l"
git-tree-sha1 = "35355fe56af8e6bd7c712f2a513a157a3ce9dccd"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "1d4e08bb08561ba51a91aebf53a4c637491bb5a91647fc6c40979978a9197f54"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.arm-linux-gnueabihf.tar.gz"
[[Libuuid]]
arch = "armv7l"
git-tree-sha1 = "3e76a7c933df13b4f64ce8893fcd8b1d69c32d7a"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "767baf8d2156199917e56a03f2d62f82f65d8b460d5b3f847c14e630712388f8"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.34.0+3/Libuuid.v2.34.0.arm-linux-musleabihf.tar.gz"
